-- MySQL Script generated by MySQL Workbench
-- mar 19 nov 2019 22:27:21 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema secretaria_administrativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema secretaria_administrativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `secretaria_administrativa` ;
USE `secretaria_administrativa` ;

-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`Roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`usuarios` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `idRoles` INT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `idRoles_idx` (`idRoles` ASC) VISIBLE,
  CONSTRAINT `idRoles`
    FOREIGN KEY (`idRoles`)
    REFERENCES `secretaria_administrativa`.`Roles` (`idRoles`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`solicitud_reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`solicitud_reporte` (
  `idformulario_reporte` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `fecha_solicitud` DATE NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_damage` DATE NULL,
  `idusuarios` INT NULL,
  PRIMARY KEY (`idformulario_reporte`),
  INDEX `idusuarios_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `idusuarios`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `secretaria_administrativa`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`Materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`Materiales` (
  `idMateriales` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idMateriales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`formulario_mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`formulario_mantenimiento` (
  `idformulario_mantenimiento` INT NOT NULL,
  `fecha_inspeccion` DATE NULL,
  `nombre_inspeccion` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `idformulario_reporte` INT NULL,
  `idMateriales` INT NULL,
  PRIMARY KEY (`idformulario_mantenimiento`),
  INDEX `idformulario_reporte_idx` (`idformulario_reporte` ASC) VISIBLE,
  INDEX `idMateriales_idx` (`idMateriales` ASC) VISIBLE,
  CONSTRAINT `idformulario_reporte`
    FOREIGN KEY (`idformulario_reporte`)
    REFERENCES `secretaria_administrativa`.`solicitud_reporte` (`idformulario_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idMateriales`
    FOREIGN KEY (`idMateriales`)
    REFERENCES `secretaria_administrativa`.`Materiales` (`idMateriales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `accion` VARCHAR(45) NULL,
  `constructor` VARCHAR(45) NULL,
  PRIMARY KEY (`idPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `secretaria_administrativa`.`RolPermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `secretaria_administrativa`.`RolPermiso` (
  `Roles_idRoles` INT NULL,
  `Permisos_idPermisos` INT NULL,
  `idRolPermiso` INT NOT NULL,
  PRIMARY KEY (`idRolPermiso`),
  INDEX `fk_Roles_has_Permisos_Roles1_idx` (`Roles_idRoles` ASC) VISIBLE,
  INDEX `fk_Roles_has_Permisos_Permisos1_idx` (`Permisos_idPermisos` ASC) VISIBLE,
  CONSTRAINT `fk_Roles_has_Permisos_Roles1`
    FOREIGN KEY (`Roles_idRoles`)
    REFERENCES `secretaria_administrativa`.`Roles` (`idRoles`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Roles_has_Permisos_Permisos1`
    FOREIGN KEY (`Permisos_idPermisos`)
    REFERENCES `secretaria_administrativa`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
